/*----------------------------------------------------------------
  ConvertOBJ.h

  Wavefront OBJ exporter for the CIFF scene format.
  Emits two files side by side:
    - <target>.obj  : geometry (v / f) grouped per node, with usemtl per color
    - <target>.mtl  : material palette (Kd from CIFF rgb)
----------------------------------------------------------------*/

#pragma once

#include <cstdarg>
#include <cstdio>
#include <filesystem>
#include <stdexcept>
#include <string>

#include "Convert.h"
#include "ProcessCIFF.h"
#include "Util.h"
#include "WriteBuffer.h"

namespace obj
{
	using namespace std;

	inline void write(WriteBuffer& write, const string& str)
	{
		write.write(str);
	}

	inline void write(WriteBuffer& write, const char* format, ...)
	{
		char tempBuffer[1024];

		va_list args;
		va_start(args, format);
		const int len = vsnprintf(tempBuffer, sizeof(tempBuffer), format, args);
		va_end(args);

		if (len < 0)
			throw runtime_error("Error formatting string in WriteBuffer");

		if (static_cast<size_t>(len) >= sizeof(tempBuffer))
			throw overflow_error("Formatted string exceeds temporary buffer size");

		write.write(tempBuffer, static_cast<size_t>(len));
	}

	inline string fileName(const string& file)
	{
		return filesystem::path(file).filename().string();
	}

	inline string materialName(const size_t index)
	{
		return "material_" + to_string(index);
	}

	struct Header
	{
		static void Write(ciff::Convert& convert, const string& mtllib)
		{
			obj::write(convert.write, "# Generated by FalconCoding CogniteCIFF\n");
			obj::write(convert.write, "# Source: " + fileName(convert.source_file) + "\n");
			obj::write(convert.write, "# Target: " + fileName(convert.target_file) + "\n");
			obj::write(convert.write, "# Date  : " + current_date_time() + "\n\n");
			obj::write(convert.write, "mtllib " + mtllib + "\n\n");
		}
	};

	struct MtlFile
	{
		static void Write(const string& path, const ciff::Read& data)
		{
			WriteBuffer mtl(path);

			obj::write(mtl, "# Generated by FalconCoding CogniteCIFF\n\n");

			for (size_t i = 0; i < data.colors.size(); ++i)
			{
				const auto& c = data.colors[i];
				const auto r = static_cast<float>(c.r) / 255.0f;
				const auto g = static_cast<float>(c.g) / 255.0f;
				const auto b = static_cast<float>(c.b) / 255.0f;
				const auto d = static_cast<float>(c.a) / 255.0f;

				obj::write(mtl, "newmtl " + materialName(i) + "\n");
				obj::write(mtl, "Ka 0.000 0.000 0.000\n");
				obj::write(mtl, "Kd %.3f %.3f %.3f\n", r, g, b);
				obj::write(mtl, "Ks 0.000 0.000 0.000\n");
				obj::write(mtl, "d  %.3f\n", d);
				obj::write(mtl, "illum 1\n\n");
			}
		}
	};

	struct Convert final : ciff::Convert
	{
		size_t vertexBase = 0;
		size_t currentMaterial = max_size;

		explicit Convert(ciff::Read& data) : ciff::Convert(data)
		{
		}

		void WriteHeader() override
		{
			const auto target = filesystem::path(target_file);
			const auto mtllib = target.stem().string() + ".mtl";
			const auto mtlPath = (target.parent_path() / mtllib).string();

			Header::Write(*this, mtllib);
			MtlFile::Write(mtlPath, data);
		}

		void WriteNode(const ciff::Node& node) override
		{
			if (node.geometries.empty())
				return;

			obj::write(write, "g " + node.name + "\n");
		}

		void WriteGeometry(const ciff::Node&, const size_t geometryIndex) override
		{
			const auto mesh = ciff::TessellateGeometry(data, geometryIndex);

			if (mesh.empty())
				return;

			if (mesh.color != currentMaterial)
			{
				obj::write(write, "usemtl " + materialName(mesh.color) + "\n");
				currentMaterial = mesh.color;
			}

			for (const auto& point : mesh.vertices)
				obj::write(write, "v %.6f %.6f %.6f\n", point.x, point.y, point.z);

			const auto base = static_cast<int64_t>(vertexBase);

			for (uint32_t t = 0; t < mesh.triangles(); ++t)
			{
				const auto v1 = static_cast<int64_t>(mesh.indices[3 * t + 0]) + base + 1;
				const auto v2 = static_cast<int64_t>(mesh.indices[3 * t + 1]) + base + 1;
				const auto v3 = static_cast<int64_t>(mesh.indices[3 * t + 2]) + base + 1;
				obj::write(write, "f %lld %lld %lld\n", v1, v2, v3);
			}

			vertexBase += mesh.points();
			obj::write(write, "\n");
		}

		void WriteMaterial(bool) override
		{
		}

		void WriteFooter() override
		{
		}
	};

	inline bool convert(ciff::Read& data)
	{
		return Convert(data).run();
	}
} // namespace obj
