/*----------------------------------------------------------------
  ConvertOBJ.h

  Wavefront OBJ exporter for the CIFF scene format.
  Emits two files side by side:
    - <target>.obj  : geometry (v / f) grouped per node, with usemtl per color
    - <target>.mtl  : material palette (Kd from CIFF rgb)
----------------------------------------------------------------*/

#pragma once

#include <algorithm>
#include <cstdarg>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <limits>
#include <stdexcept>
#include <string>
#include <system_error>
#include <vector>

#include "Convert.h"
#include "ConvertAsync.h"
#include "MeshNormals.h"
#include "ProcessCIFF.h"
#include "Util.h"
#include "WriteBuffer.h"

namespace obj
{
	using namespace std;

	inline void write(WriteBuffer& write, const string& str)
	{
		write.write(str);
	}

	inline void write(WriteBuffer& write, const char* format, ...)
	{
		char tempBuffer[1024];

		va_list args;
		va_start(args, format);
		const int len = vsnprintf(tempBuffer, sizeof(tempBuffer), format, args);
		va_end(args);

		if (len < 0)
			throw runtime_error("Error formatting string in WriteBuffer");

		if (static_cast<size_t>(len) >= sizeof(tempBuffer))
			throw overflow_error("Formatted string exceeds temporary buffer size");

		write.write(tempBuffer, static_cast<size_t>(len));
	}

	inline string fileName(const string& file)
	{
		return filesystem::path(file).filename().string();
	}

	inline string materialName(const size_t index)
	{
		return "material_" + to_string(index);
	}

	inline filesystem::path materialPath(const string& targetFile)
	{
		const auto target = filesystem::path(targetFile);
		return target.parent_path() / (target.stem().string() + ".mtl");
	}

	struct Header
	{
		static void Write(ciff::Convert& convert, const string& mtllib)
		{
			obj::write(convert.write, "# Generated by FalconCoding CogniteCIFF\n");
			obj::write(convert.write, "# Source: " + fileName(convert.source_file) + "\n");
			obj::write(convert.write, "# Target: " + fileName(convert.target_file) + "\n");
			obj::write(convert.write, "# Date  : " + current_date_time() + "\n\n");
			obj::write(convert.write, "mtllib " + mtllib + "\n\n");
		}
	};

	struct MtlFile
	{
		static void Write(const string& path, const ciff::Read& data)
		{
			constexpr size_t bufferSize = 1ULL * 1024ULL * 1024ULL;
			WriteBuffer mtl(path, bufferSize);

			obj::write(mtl, "# Generated by FalconCoding CogniteCIFF\n\n");

			for (size_t i = 0; i < data.colors.size(); ++i)
			{
				const auto& c = data.colors[i];
				const auto r = static_cast<float>(c.r) / 255.0f;
				const auto g = static_cast<float>(c.g) / 255.0f;
				const auto b = static_cast<float>(c.b) / 255.0f;
				const auto d = static_cast<float>(c.a) / 255.0f;

				obj::write(mtl, "newmtl " + materialName(i) + "\n");
				obj::write(mtl, "Ka 0.000 0.000 0.000\n");
				obj::write(mtl, "Kd %.3f %.3f %.3f\n", r, g, b);
				obj::write(mtl, "Ks 0.000 0.000 0.000\n");
				obj::write(mtl, "d  %.3f\n", d);
				obj::write(mtl, "illum 1\n\n");
			}

			mtl.close();
		}
	};

	struct Convert final : ciff::Convert
	{
		struct MaterialEvent final
		{
			size_t byteOffset = 0;
			size_t materialIndex = 0;
		};

		struct AsyncChunkState final
		{
			vector<MaterialEvent> materialEvents;
		};

		explicit Convert(ciff::Read& data, const size_t writeBufferSize = WRITE_BUFFER_SIZE)
			: ciff::Convert(data, writeBufferSize)
		{
		}

		void PrepareAsyncChunk(AsyncChunkState& state)
		{
			state.materialEvents.clear();
			asyncChunk = &state;
			currentMaterial = max_size;
		}

		void BeginAsyncMerge()
		{
			asyncChunk = nullptr;
			asyncMerge = true;
			currentMaterial = max_size;
		}

		void PrepareAsyncChunkForMerge(AsyncChunkState&)
		{
			if (!asyncMerge)
				throw logic_error("OBJ async merge has not been initialized");
		}

		void MergeAsyncChunk(const filesystem::path& shardFile, const AsyncChunkState& state,
			const bool outputEnabled)
		{
			if (!asyncMerge)
				throw logic_error("OBJ async merge has not been initialized");

			if (!outputEnabled)
			{
				for (const auto& event : state.materialEvents)
					ReplayMaterialEvent(event);
				return;
			}

			if (state.materialEvents.empty())
			{
				write.append(shardFile.string(), false);
				return;
			}

			ifstream input(shardFile, ios::binary);
			if (!input.is_open())
				throw runtime_error("Unable to open OBJ async shard for merging");

			error_code error;
			const auto fileSize = filesystem::file_size(shardFile, error);
			if (error)
				throw system_error(error, "Unable to inspect OBJ async shard");
			if (fileSize > numeric_limits<size_t>::max())
				throw length_error("OBJ async shard exceeds size_t range");

			if (mergeBuffer.empty())
				mergeBuffer.resize(1ULL * 1024ULL * 1024ULL);

			size_t position = 0;
			const auto copyBytes = [&](size_t count)
			{
				while (count != 0)
				{
					const auto blockSize = min(count, mergeBuffer.size());
					input.read(mergeBuffer.data(), static_cast<streamsize>(blockSize));
					if (input.gcount() != static_cast<streamsize>(blockSize))
						throw runtime_error("Unable to read complete OBJ async shard");

					write.write(mergeBuffer.data(), blockSize);
					position += blockSize;
					count -= blockSize;
				}
			};

			const auto shardSize = static_cast<size_t>(fileSize);
			for (const auto& event : state.materialEvents)
			{
				if (event.byteOffset < position || event.byteOffset > shardSize)
					throw runtime_error("OBJ async material event lies outside its shard");

				copyBytes(event.byteOffset - position);
				ReplayMaterialEvent(event);
			}
			copyBytes(shardSize - position);
		}

		void CommitAsyncMerge() noexcept
		{
			asyncMerge = false;
		}

		[[nodiscard]] vector<filesystem::path> AsyncSidecarFiles() const
		{
			return { materialPath(target_file) };
		}

		void WriteMaterialReference(const size_t materialIndex)
		{
			if (currentMaterial == materialIndex)
				return;

			currentMaterial = materialIndex;
			if (asyncChunk)
			{
				asyncChunk->materialEvents.push_back({ write.tell(), materialIndex });
				return;
			}

			obj::write(write, "usemtl " + materialName(materialIndex) + "\n");
		}

		void WriteHeader() override
		{
			currentMaterial = max_size;
			const auto mtlPath = materialPath(target_file);

			Header::Write(*this, mtlPath.filename().string());
			MtlFile::Write(mtlPath.string(), data);
		}

		void WriteNode(const ciff::Node& node) override
		{
			if (node.geometries.empty())
				return;

			obj::write(write, "g " + node.name + "\n");
		}

		void WriteGeometry(const ciff::Node&, const size_t geometryIndex) override
		{
			const auto& geometry = data.getGeometry(geometryIndex);
			const auto mesh = geometry.primitive == ciff::Type::Mesh
				? ciff::normal_processing::FinalizeMeshNormals(data.getMesh(geometry.mesh))
				: ciff::normal_processing::FinalizeMeshNormals(ciff::TessellateGeometry(data, geometryIndex));

			if (mesh.empty())
				return;

			WriteMaterialReference(geometry.color);

			for (size_t i = 0; i < mesh.positions.size(); i += 3)
				obj::write(write, "v %.9g %.9g %.9g\n",
				           mesh.positions[i], mesh.positions[i + 1], mesh.positions[i + 2]);

			for (size_t i = 0; i < mesh.normals.size(); i += 3)
				obj::write(write, "vn %.9g %.9g %.9g\n",
				           mesh.normals[i], mesh.normals[i + 1], mesh.normals[i + 2]);

			const auto points = static_cast<int64_t>(mesh.points());

			for (uint32_t t = 0; t < mesh.triangles(); ++t)
			{
				const auto v1 = static_cast<int64_t>(mesh.indices[3 * t + 0]) - points;
				const auto v2 = static_cast<int64_t>(mesh.indices[3 * t + 1]) - points;
				const auto v3 = static_cast<int64_t>(mesh.indices[3 * t + 2]) - points;
				obj::write(write, "f %lld//%lld %lld//%lld %lld//%lld\n",
				           v1, v1, v2, v2, v3, v3);
			}

			obj::write(write, "\n");
		}

		void WriteMaterial(bool) override
		{
		}

		void WriteFooter() override
		{
		}

	private:
		void ReplayMaterialEvent(const MaterialEvent& event)
		{
			WriteMaterialReference(event.materialIndex);
		}

		AsyncChunkState* asyncChunk = nullptr;
		bool asyncMerge = false;
		size_t currentMaterial = max_size;
		vector<char> mergeBuffer;
	};

	inline bool convert(ciff::Read& data)
	{
		return cmd::async ? ConvertAsync<Convert>(data).run() : Convert(data).run();
	}
} // namespace obj
